version: "3.9"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: jarvisdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jarvis-network

  redis:
    image: redis:7
    restart: always
    networks:
      - jarvis-network

  initdb:
    build: ./jarvis-web/backend
    command: python init_db.py
    environment:
      DATABASE_URL: postgresql://jarvis:securepass@postgres:5432/jarvisdb
    depends_on:
      - postgres
    networks:
      - jarvis-network

  backend:
    build: ./jarvis-web/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./jarvis-web/backend:/app
    env_file:
      - .env
    depends_on:
      - initdb
      - redis
    networks:
      - jarvis-network

  frontend:
    build: ./jarvis-web/frontend
    volumes:
      - ./jarvis-web/frontend:/app
    networks:
      - jarvis-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./jarvis-web/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - jarvis-network

volumes:
  postgres_data:

networks:
  jarvis-network:
